name: lotto-manual-update

on:
  workflow_dispatch:   # 버튼 눌러 실행

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install pandas openpyxl

      - run: python main.py

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "manual update lotto data"
          git push
